[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo_mysql", "php82Extensions.bcmath", "php82Extensions.gd", "composer", "nodejs", "npm"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader", "npm install", "npm run build", "php artisan optimize"]

[start]
cmd = "php artisan migrate --force && vendor/bin/heroku-php-apache2 public/"
